version: 1.0.{build}
image:
  - Visual Studio 2017
  - macos
for:
  -
    matrix:
      only:
        - image: Visual Studio 2017
    init:
    - cmd: >-
        curl -sSf https://win.rustup.rs -o rustup-init.exe
    
        rustup-init.exe --default-host x86_64-pc-windows-msvc -y
    
        del /F rustup-init.exe
    
        set PATH=%PATH%;C:\\Libraries\\llvm-5.0.0\\bin;C:\\Users\\appveyor\\.cargo\\bin
    
        llvm-config --version
    
        rustc -Vv
    
        cargo -V
    build: off
    test_script:
    - cmd: >-
        cargo test
    
        .\target\debug\examples\jit-function.exe

  -
    matrix:
      only:
        - image: macos
    install:
      - sh: >-
          brew install llvm
      - sh: >-
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs -o rustup.sh && sh rustup.sh -y
    build: off
    test_script:
      - sh: |
          export PATH=/usr/local/bin:$PATH
          source ~/.cargo/env
          export LLVM_SYS_100_PREFIX=/usr/local/opt/llvm
          export LLVM_CONFIG_PATH=${LLVM_SYS_100_PREFIX}/bin/llvm-config

          cargo test
          cargo run --example nop-function
          cargo run --example jit-function
          echo "Hello, world!" | cargo run --example disassembler
