image: ubuntu:xenial

pipelines:
  default:
    - step:
        script:
          - apt-get update && apt-get install -y curl file sudo mercurial xz-utils build-essential libffi-dev zlib1g-dev
          - echo deb http://apt.llvm.org/xenial/ llvm-toolchain-xenial-7 main >> /etc/apt/sources.list
          - curl https://apt.llvm.org/llvm-snapshot.gpg.key| apt-key add -
          - apt-get update && apt-get install -y llvm-7 llvm-7-dev
          - curl https://sh.rustup.rs -sSf | CARGO_HOME=$HOME/rust sh -s -- -y
          - PATH=$PATH:~/rust/bin LLVM_SYS_70_PREFIX=/usr/lib/llvm-7 LLVM_SYS_70_FFI_WORKAROUND=1 cargo test
          - ./target/debug/examples/jit-function
